<?php

class Controller_404 extends Controller
{
    function action_index()
    {
//        parent::action_index(); // TODO: Change the autogenerated stub
        $this->view->generate('404_view.php', 'template_view.php');
    }
}