<?php

class Controller_Services extends Controller
{
    function action_index()
    {
//        parent::action_index(); // TODO: Change the autogenerated stub
        $this->view->generate('services_view.php', 'template_view.php');
    }
}